Repository NREL/COMPASS, pull requests merged in 2025-06, with the labels that each got.

#134 Minor updates
  INSTALL.rst
  compass/extraction/common.py
  compass/extraction/solar/ordinance.py
  compass/extraction/solar/parse.py
  compass/extraction/wind/ordinance.py
  compass/extraction/wind/parse.py
  compass/scripts/process.py
  compass/utilities/parsing.py
  compass/validation/content.py
Labels: enhancement, p-medium, topic-python-llm

#135 Update location
  compass/_cli.py
  compass/data/conus_jurisdictions.csv
  compass/extraction/common.py
  compass/extraction/date.py
  compass/extraction/solar/__init__.py
  compass/extraction/solar/graphs.py
  compass/extraction/solar/ordinance.py
  compass/extraction/solar/parse.py
  compass/extraction/tree.py
  compass/extraction/wind/__init__.py
  compass/extraction/wind/graphs.py
  compass/extraction/wind/ordinance.py
  compass/extraction/wind/parse.py
  compass/llm/calling.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/cpu.py
  compass/services/threaded.py
  compass/utilities/__init__.py
  compass/utilities/counties.py
  compass/utilities/enums.py
  compass/utilities/jurisdictions.py
  compass/utilities/location.py
  compass/validation/content.py
  compass/validation/graphs.py
  compass/validation/location.py
  docs/source/dev/README.rst
  examples/execution_basics/README.rst
  support/conus_counties_compiled_2024.csv
  support/update_jurisdictions.py
  tests/python/test_integrated.py
  tests/python/utilities/test_utilities_counties.py
  tests/python/utilities/test_utilities_jurisdictions.py
  tests/python/utilities/test_utilities_location.py
  tests/python/validation/test_validation_graphs.py
  tests/python/validation/test_validation_location.py
Labels: enhancement, topic-python-llm, p-high

#136 Deprecate one-shot validators
  compass/extraction/common.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/openai.py
  compass/validation/graphs.py
  compass/validation/location.py
  pixi.lock
  pyproject.toml
  tests/python/data_files/Allegany New York.pdf
  tests/python/services/test_services_openai.py
  tests/python/test_integrated.py
  tests/python/validation/test_validation_location.py
Labels: breaking, deprecation, p-medium, topic-python-llm

#141 Using Anyhow in DB-Command Line
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  crates/cli/src/main.rs
Labels: enhancement

#143 Fix GHA
  .github/workflows/docs.yml
  .github/workflows/publish_to_pypi.yml
Labels: chore, p-high

#144 GHA fixes
  .github/workflows/docs.yml
  .github/workflows/publish_to_pypi.yml
Labels: chore, p-high

#142 Prompt Updates
  compass/common/base.py
  compass/extraction/features.py
  compass/extraction/ngrams.py
  compass/extraction/solar/graphs.py
  compass/extraction/solar/parse.py
  compass/extraction/wind/graphs.py
  compass/extraction/wind/parse.py
  compass/validation/graphs.py
Labels: enhancement, bugfix, topic-python-llm, p-high

#145 Fix PyPi build action
  .github/workflows/publish_to_pypi.yml
Labels: chore

#146 Add tags to PyPi build action
  .github/workflows/publish_to_pypi.yml
Labels: chore

#147 DB schema
  docs/diagram/compass-db.dot
  docs/diagram/compass-db.svg
  docs/diagram/run.sh
  pixi.lock
  pyproject.toml
Labels: documentation

#150 Reconcile module source
  crates/compass/src/scraper/jurisdiction.rs
  crates/compass/src/scraper/mod.rs
  crates/compass/src/scraper/source.rs
Labels: refactor

#151 Update `jurisdiction.json` parsing and loading
  crates/compass/src/scraper/source.rs
Labels: bugfix, p-critical, topic-rust-duckdb

#154 Freeze cargo in CI
  .github/workflows/ci-rust.yml
Labels: chore, p-high

#155 Update lockfiles
  .github/workflows/ci-rust.yml
  Cargo.lock
  pixi.lock
Labels: chore

#152 Fix usage ingestion
  crates/compass/src/scraper/usage.rs
Labels: bugfix, p-critical, topic-rust-duckdb

#156 Update DB diagram
  docs/diagram/compass-db.dot
  docs/diagram/compass-db.svg
Labels: documentation, enhancement, p-medium

#149 Update defaults
  compass/llm/config.py
Labels: enhancement, p-low, topic-python-llm

#157 Location name now correctly prefixed
  compass/utilities/location.py
  compass/validation/graphs.py
  compass/validation/location.py
  tests/python/utilities/test_utilities_location.py
  tests/python/validation/test_validation_graphs.py
Labels: enhancement, p-medium

#159 Adjust AHJ
  compass/data/conus_jurisdictions.csv
  crates/compass/src/lib.rs
Labels: enhancement, p-high

#160 Update lockfiles
  Cargo.lock
  Cargo.toml
  crates/cli/Cargo.toml
  pixi.lock
Labels: chore, dependencies

#162 Rust GHA update
  .github/workflows/ci-rust.yml
  pixi.lock
  pyproject.toml
Labels: enhancement, chore, p-high

#163 Fix name of binary in GHA
  .github/workflows/release-cli.yml
Labels: chore

#166 Capitalization updates
  compass/utilities/__init__.py
  compass/utilities/base.py
  compass/utilities/jurisdictions.py
  compass/utilities/location.py
  tests/python/utilities/test_utilities_base.py
  tests/python/utilities/test_utilities_jurisdictions.py
  tests/python/utilities/test_utilities_location.py
Labels: enhancement, p-medium

#167 Update defaults
  compass/llm/config.py
  compass/scripts/process.py
  compass/utilities/__init__.py
Labels: enhancement, p-low

#170 Update to newest elm version
  Cargo.lock
  pixi.lock
  pyproject.toml
Labels: enhancement, chore, dependencies

#172 Add website scraper
  INSTALL.rst
  README.rst
  compass/common/base.py
  compass/data/conus_jurisdictions.csv
  compass/extraction/solar/__init__.py
  compass/extraction/solar/ordinance.py
  compass/extraction/solar/parse.py
  compass/extraction/wind/__init__.py
  compass/extraction/wind/ordinance.py
  compass/extraction/wind/parse.py
  compass/llm/calling.py
  compass/pb.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/threaded.py
  compass/utilities/base.py
  compass/utilities/enums.py
  compass/validation/location.py
  crates/compass/src/scraper/source.rs
  docs/diagram/compass-db.dot
  docs/diagram/compass-db.svg
  tests/python/validation/test_validation_location.py
Labels: enhancement, topic-python-general, p-high

#173 Upgrade deps
  Cargo.lock
  compass/scripts/process.py
  pixi.lock
  pyproject.toml
Labels: enhancement, dependencies, p-medium

#176 Update lockfiles
  Cargo.lock
  pixi.lock
Labels: chore
