Repository NREL/COMPASS, pull requests merged in 2025-07, with the labels that each got.

#183 Processing ordinance files - Async
  crates/compass/src/scraper/source.rs
Labels: p-low, refactor, topic-rust-general

#185 Explicitly defined `edition` pattern to be used by the formatter
  rustfmt.toml
Labels: p-low, topic-rust-general

#189 Minor updates
  compass/scripts/download.py
  pixi.lock
  pyproject.toml
  tests/python/services/test_services_cpu.py
  tests/python/services/test_services_threaded.py
Labels: enhancement, dependencies, p-medium

#191 Add more to PDF doc attrs
  compass/services/cpu.py
  compass/services/threaded.py
  compass/web/website_crawl.py
  crates/compass/src/scraper/source.rs
  docs/diagram/compass-db.dot
  docs/diagram/compass-db.svg
Labels: enhancement
