Repository NREL/COMPASS, pull requests merged in 2025-09, with the labels that each got.

#232 FIPS requires more than u64 to fit all possible values
  crates/compass/src/lib.rs
  crates/compass/src/scraper/ordinance/qualitative.rs
  crates/compass/src/scraper/ordinance/quantitative.rs
  crates/compass/src/scraper/source.rs
Labels: bugfix, p-critical

#237 Broken duckdb-1.4.0 on windows
  .github/workflows/docker-publish.yml
  Cargo.lock
  Cargo.toml
  pixi.lock
  pyproject.toml
Labels: bugfix

#236 Update ELM dep
  pixi.lock
  pyproject.toml
Labels: dependencies, topic-python-llm, p-high
