Repository NREL/COMPASS, pull requests merged in 2025-04, with the labels that each got.

#87 Remove check that stops docs from building
  .github/workflows/docs.yml
Labels: documentation, chore

#89 Fix links in README
  README.rst
Labels: documentation, enhancement, chore

#91 Clarify instructions
  docs/source/dev/README.rst
Labels: documentation, enhancement

#92 Update build process and dependencies
  .github/workflows/docs.yml
  .github/workflows/publish_to_pypi.yml
  pixi.lock
  pyproject.toml
Labels: enhancement, chore, dependencies, topic-python-general

#93 Usage now tracks model used
  compass/services/openai.py
  compass/services/usage.py
  tests/python/services/test_services_usage.py
Labels: enhancement, new computation, topic-python-llm, p-high

#94 Refactor scripts
  compass/scripts/process.py
Labels: p-medium, refactor, topic-python-cli

#97 No kwargs passed around in scripts
  compass/_cli.py
  compass/extraction/apply.py
  compass/llm/__init__.py
  compass/llm/calling.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/provider.py
  compass/services/threaded.py
Labels: p-medium, refactor, topic-python-llm

#98 Costs in PB
  compass/_cli.py
  compass/pb.py
  compass/scripts/process.py
  compass/services/openai.py
  compass/utilities/__init__.py
Labels: enhancement, p-low, topic-python-cli

#99 Allow using different LLM's for different parsing tasks
  compass/extraction/apply.py
  compass/extraction/common.py
  compass/extraction/date.py
  compass/extraction/solar/ordinance.py
  compass/extraction/tree.py
  compass/extraction/wind/ordinance.py
  compass/llm/calling.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/openai.py
  compass/utilities/enums.py
  compass/validation/content.py
  compass/validation/location.py
Labels: enhancement, new computation, p-high

#102 Costs in meta
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/threaded.py
Labels: enhancement, p-medium, topic-python-cli

#103 Start Examples directory
  INSTALL.rst
  README.rst
  compass/llm/calling.py
  compass/pb.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/base.py
  compass/services/cpu.py
  compass/services/openai.py
  compass/services/queues.py
  compass/services/threaded.py
  compass/services/usage.py
  compass/utilities/__init__.py
  compass/utilities/location.py
  compass/utilities/parsing.py
  docs/source/dev/README.rst
  docs/source/examples/basic_run
  docs/source/examples/index.rst
  docs/source/index.rst
  examples/basic_run/README.rst
  examples/basic_run/config_bare_minimum.json5
  examples/basic_run/config_kitchen_sink.json5
  examples/basic_run/config_recommended.json5
  examples/basic_run/jurisdictions.csv
Labels: documentation, enhancement, p-medium

#104 Add quickstart demo
  .github/workflows/ci-rust.yml
  INSTALL.rst
  README.rst
  compass/_cli.py
  compass/scripts/process.py
  docs/source/dev/README.rst
  docs/source/examples/execution_basics
  docs/source/examples/index.rst
  examples/execution_basics/README.rst
  examples/execution_basics/config_bare_minimum.json5
  examples/execution_basics/config_kitchen_sink.json5
  examples/execution_basics/config_recommended.json5
  examples/execution_basics/jurisdictions.csv
  examples/openai_solar_demo/README.rst
  examples/openai_solar_demo/config.json5
  examples/openai_solar_demo/jurisdictions.csv
  pixi.lock
  pyproject.toml
Labels: documentation, enhancement, p-high

#105 Update pixi version in GHA
  .github/workflows/docs.yml
  .github/workflows/publish_to_pypi.yml
Labels: documentation, bugfix, p-critical, topic-python-general

#106 Delete unused docs
  docs/source/examples/basic_run
  examples/basic_run/README.rst
  examples/basic_run/config_bare_minimum.json5
  examples/basic_run/config_kitchen_sink.json5
  examples/basic_run/config_recommended.json5
  examples/basic_run/jurisdictions.csv
Labels: documentation, p-medium

#109 Add top-level examples README
  docs/source/conf.py
  docs/source/dev/README.rst
  examples/README.md
  examples/openai_solar_demo/README.rst
  examples/parse_existing_docs/README.rst
  pixi.lock
  pyproject.toml
Labels: documentation, enhancement, p-medium

#110 Date extraction in separate function
  compass/extraction/__init__.py
  compass/extraction/apply.py
  compass/scripts/download.py
  compass/scripts/process.py
  examples/parse_existing_docs/README.rst
  examples/parse_existing_docs/parse_pdf.py
Labels: p-medium, refactor, topic-python-general

#111 Fix error message
  compass/extraction/apply.py
Labels: bugfix, p-low, topic-python-general

#112 Rename features
  compass/extraction/apply.py
  compass/extraction/common.py
  compass/extraction/features.py
  compass/extraction/solar/parse.py
  compass/extraction/wind/parse.py
  pixi.lock
  pyproject.toml
Labels: breaking, p-medium, refactor, topic-python-llm

#113 Refactor out `LLMConfig` interface
  compass/extraction/apply.py
  compass/llm/__init__.py
  compass/llm/calling.py
  compass/llm/config.py
  compass/scripts/download.py
  compass/scripts/process.py
  examples/parse_existing_docs/README.rst
  examples/parse_existing_docs/parse_pdf.py
Labels: p-medium, refactor, topic-python-llm

#115 Logging updates
  compass/__init__.py
  compass/_cli.py
  compass/exceptions.py
  compass/extraction/apply.py
  compass/extraction/common.py
  compass/extraction/solar/ordinance.py
  compass/extraction/solar/parse.py
  compass/extraction/tree.py
  compass/extraction/wind/ordinance.py
  compass/extraction/wind/parse.py
  compass/pb.py
  compass/scripts/download.py
  compass/scripts/process.py
  compass/services/cpu.py
  compass/services/threaded.py
  compass/utilities/counties.py
  compass/utilities/logs.py
  compass/validation/content.py
  compass/validation/location.py
  examples/parse_existing_docs/README.rst
  examples/parse_existing_docs/parse_pdf.py
Labels: enhancement, p-medium, topic-python-async

#116 Allow user to black-list domains
  compass/_cli.py
  compass/scripts/download.py
  compass/scripts/process.py
Labels: enhancement, bugfix, p-medium, topic-python-cli

#117 Prompt updates
  compass/extraction/common.py
  compass/extraction/solar/parse.py
  compass/extraction/wind/parse.py
Labels: enhancement, p-medium, topic-python-llm

#118 Update county validators
  compass/extraction/solar/ordinance.py
  compass/validation/location.py
Labels: enhancement, topic-python-llm, p-high

#107 Quantitative Ordinance
  Cargo.lock
  crates/compass/src/lib.rs
  crates/compass/src/scraper/mod.rs
  crates/compass/src/scraper/ordinance.rs
Labels: topic-rust-duckdb, p-high

#120 Filter output CSV
  compass/scripts/process.py
  compass/utilities/__init__.py
  compass/utilities/parsing.py
  examples/parse_existing_docs/README.rst
  examples/parse_existing_docs/parse_pdf.py
Labels: enhancement, topic-python-general, p-high

#121 Use tag for OpenAI services
  compass/llm/config.py
  compass/services/base.py
  compass/services/openai.py
Labels: enhancement, p-medium, topic-python-llm, topic-python-cli

#122 Add parts of date to JSON file
  compass/services/threaded.py
Labels: enhancement, breaking, topic-python-cli, p-high

#119 Loading target jurisdictions on new format
  crates/compass/src/scraper/jurisdiction.rs
  crates/compass/src/scraper/mod.rs
  crates/compass/src/scraper/source.rs
Labels: topic-rust-duckdb, p-high

#124 Fix task for pixi v0.46
  pixi.lock
  pyproject.toml
Labels: bugfix, p-critical, topic-python-cli

#125 Add citation file
  CITATION.cff
Labels: chore

#123 Loading qualitative ordinances
  crates/compass/src/scraper/mod.rs
  crates/compass/src/scraper/ordinance/mod.rs
  crates/compass/src/scraper/ordinance/qualitative.rs
  crates/compass/src/scraper/ordinance/quantitative.rs
Labels: topic-rust-duckdb, p-high
